//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingChallenge.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Title
    {
        public int TitleId { get; set; }
        public string Name { get; set; }
        public string Symbol { get; set; }
        public decimal Last { get; set; }
        public decimal Var_ { get; set; }
        public string CapMarket { get; set; }
        public decimal Volume { get; set; }
    }
}
